#!/usr/bin/python
"""
Query SGE account information on the cluster

USAGE: qacct [OPTIONS]
"""

__author__ = "Mark Palmeri (mlp6)"
__email__ = "mark.palmeri@duke.edu"
__date__ = "2010-11-01"

import sys
import os

def usage():
    print "USAGE: qacct [OPTIONS]"

if len(sys.argv) > 1:
    OPTIONS = " ".join(sys.argv[1:])
    SSH_CMD = "ssh hogwarts.egr.duke.edu \"qacct %s\"" % OPTIONS
else:
    SSH_CMD = "ssh hogwarts.egr.duke.edu \"qacct\""

print SSH_CMD

os.system(SSH_CMD)
