#!/usr/bin/python
"""
Release held SGE jobs 

USAGE: qrls [OPTIONS]
"""

__author__ = "Mark Palmeri (mlp6)"
__email__ = "mark.palmeri@duke.edu"
__date__ = "2011-01-08"

import sys
import os

def usage():
    print "USAGE: qrls [OPTIONS]"

if len(sys.argv) > 1:
    OPTIONS = " ".join(sys.argv[1:])
    SSH_CMD = "ssh hogwarts \"qrls %s\"" % OPTIONS
else:
    SSH_CMD = "ssh hogwarts \"qrls\""

print SSH_CMD

os.system(SSH_CMD)
