#!/usr/bin/python
"""
Remove a running/queued SLURM job from the cluster.

USAGE: scancel [OPTIONS]
"""

__author__ = "Mark Palmeri (mlp6)"
__email__ = "mark.palmeri@duke.edu"
__date__ = "2015-05-06"

import sys
import os

def usage():
    print "USAGE: scancel TASK_ID"

if len(sys.argv) > 1:
    QDEL_OPTIONS = " ".join(sys.argv[1:])
else:
    print "ERROR: scancel needs a task ID"
    sys.exit()

SSH_CMD = "ssh durmstrang.egr.duke.edu \"scancel %s\"" % QDEL_OPTIONS
print SSH_CMD

os.system(SSH_CMD)
